### PR TITLE
Add 'linux-headers-amd64' as a dependency

### PR DESCRIPTION
**Pull request by waveletlet**
The `make -C /lib/modules/$(uname -r)/build M=$(pwd) clean` command fails because it can't find /lib/modules/.../build. Installing linux-headers-amd64 fixes this.

### CODE REVIEW

**Comment by waveletlet** [comment]
After some updating and `apt autoremove`ing, the module wouldn't build anymore. Apparently my linux headers disappeared. Hope this helps someone.

**Comment by kirvedx** [comment]
Oh I'm sorry, my email gets flooded and I didn't even notice a message.

The thing about building your own wifi kernel module, is that you'll have to do it every single time you install an updated kernel as well.

A change from 4.17.0-1 to 4.17.0-3 will require a rebuild of the wifi kernel module, just as a change from 4.17.0 to 4.17.1 or even 4.17 to 4.18 will.

I typically end up with **linux-headers** installed and always upgraded automatically because I almost always need them for compiling video kernel drivers via *dkms*. Though sometimes, especially if you manually install them yourself - they can become uninstalled when a new kernel version is installed and you run `apt-get autoremove`. This is because the *linux-headers* package was not a dependency to anything else, and its only tie was to the *old version of the kernel* that you're now `autoremoving` - so the *linux-headers* package will be automatically linked for removal too. 

If that is the case for you, you'll need to download the *latest* **linux-headers** every time a kernel change occurs, and subsequently recompile your wifi kernel module, following the `README.md` for installation.

A good way to tell that you need to recompile the wifi kernel module, is that you suddenly don't have wifi anymore (and `uname -r` shows a newer kernel version than before)

**Comment by kirvedx** [comment]
Great suggestion by the way, I'll definitely be merging this!

**Comment by kirvedx** [comment]
I included the change to the `README.md` for the reference of *linux-headers-amd64* in [5fce379005c5748ca9fa5e718bcc1e15d506c366](https://github.com/devrikx/atheros/commit/5fce379005c5748ca9fa5e718bcc1e15d506c366)

Thank you for your contributions!

**Pull request merged**
